movies/urls.py
from django.urls import path

from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.MovieListView.as_view(), name='index'), # edite esta linha
    path('search/', views.search_movies, name='search'),
    path('create/', views.create_movie, name='create'),
    path('<int:pk>/', views.MovieDetailView.as_view(), name='detail'), # edite esta linha
]

moviesite/urls.py
from django.contrib import admin
from django.urls import include, path 

urlpatterns = [
    path('', include('staticpages.urls')), 
    path('movies/', include('movies.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'), 
    path('', views.index, name='index'),
]

movies/models.py
from django.db import models
from django.conf import settings

class Movie(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)

    def __str__(self):
        return f'{self.name} ({self.release_year})'

class Review(models.Model):
    author = models.CharField(max_length=255)
    text = models.CharField(max_length=255)
    likes = models.IntegerField(default=0)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author}'

# Create your models here.

staticpages/models.py
from django.db import models

# Create your models here.

movies/forms.py
from django.forms import ModelForm
from .models import Movie

class MovieForm(ModelForm):
    class Meta:
        model = Movie
        fields = [
            'name',
            'release_year',
            'poster_url',
        ]

movies/views.py
from django.http import HttpResponse
from .models import Movie
from django.shortcuts import render, get_object_or_404
from .temp_data import movie_data
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from .forms import MovieForm

class MovieListView(generic.ListView):
    model = Movie
    template_name = 'movies/index.html'

class MovieDetailView(generic.DetailView):
    model = Movie
    template_name = 'movies/detail.html'

def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        context = {
            "movie_list": [
                m for m in movie_data
                if request.GET['query'].lower() in m['name'].lower()
            ]
        }
    return render(request, 'movies/search.html', context) # modifique esta linha


def create_movie(request):
    if request.method == 'POST':
        form = MovieForm(request.POST)
        if form.is_valid():
            movie_name = form.cleaned_data['name']
            movie_release_year = form.cleaned_data['release_year']
            movie_poster_url = form.cleaned_data['poster_url']
            movie = Movie(name=movie_name,
                          release_year=movie_release_year,
                          poster_url=movie_poster_url)
            movie.save()
            return HttpResponseRedirect(
                reverse('movies:detail', args=(movie.id, )))
    else:
        form = MovieForm()
    context = {'form': form}
    return render(request, 'movies/create.html', context)

staticpages/views.py
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Filme</h2>
<form method="post" action="{% url 'movies:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %} {% block title %} {{ movie.name }} ({{
    movie.release_year }} {% endblock title %} {% block content %}
    <h2>Detalhes do Filme {{ movie.name }} ({{ movie.release_year }})</h2>
    
    <section class="dados-de-filme">
      <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}" />
      <ul>
        <li>Nome: {{ movie.name }}</li>
        <li>Ano de Lançamento: {{ movie.release_year }}</li>
      </ul>
    </section>
    
    {% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %} {% block content %}
<h2>Todos os Filmes</h2>
<section>
  <p>
    Muitos resultados? <a href="{% url 'movies:search' %}">Buscar Filmes</a>
  </p>
  <p>
    Não encontrou o filme?
    <a href="{% url 'movies:create' %}">Adicionar Novo Filme</a>
  </p>
</section>
{% if movie_list %}
<section class="lista-de-cards">
  {% for movie in movie_list %}
  <article class="card">
    <a href="{% url 'movies:detail' movie.id %}">
      ><img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}"
    /></a>
    <p>{{ movie.name }} ({{ movie.release_year }})</p>
  </article>
  {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme.</p>
{% endif %} {% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Watch that film!</i></h1>
<p>A Página para Comunidade Resenhadora de Filmes</p>
{% endblock content %}

templates/base.html
{% load static %} <!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" /> <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->

</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.svg' %}"> </a> <!-- adicione esta linha -->
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'movies:index' %}">Filmes</a></li>
                <!-- adicione esta linha -->
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>